services:
  cold-diffusion-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cold-diffusion-api
    env_file:
      - stack.env
    ports:
      - "53053:53053"
    working_dir: /app
    environment:
      - T=${T}
      - GPU=${GPU}
      - RANGE_RNF=${RANGE_RNF}
      - MODEL_PATH=${MODEL_PATH}
    networks:
      - nginx-manager_customnetwork

networks:
  nginx-manager_customnetwork:
    external: true