services:
  cold-diffusion-api:
    build: .
    container_name: cold-diffusion-api
    ports:
      - "53053:53053"
    volumes:
      - .:/app  # This ensures the code is up to date inside the container
    environment:
      - PYTHONUNBUFFERED=1  # Optional: prevent output buffering (useful for logs)
