services:
  cold-diffusion-app:
    build: .
    container_name: cold-diffusion-api
    ports:
      - "53053:53053"
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "53053"]
