services:
  cold-diffusion-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cold-diffusion-api
    env_file:
      - fileName
    ports:
      - "53053:53053"
    environment:
      - T=${T}
      - GPU=${GPU}
      - RANGE_RNF=${RANGE_RNF}
      - MODEL_PATH=${MODEL_PATH}
    command: ["uvicorn", "app.test_main:app", "--host", "0.0.0.0", "--port", "53053"]