name: CDiffSD
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - cudatoolkit=11.8
  - pytorch
  - torchvision
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - scikit-learn
  - optuna
  - jupyter
  - fastapi
  - uvicorn
  - torchaudio
  - torchvision
  - pip:
      - obspy==1.4.0
      - seisbench==0.6.1
      - h5py==3.13.0